# Generated by Django 5.0.14 on 2025-12-11 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('mail_count', models.PositiveIntegerField(default=0)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folders.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '폴더',
                'verbose_name_plural': '폴더들',
                'db_table': 'folders',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['user', 'path'], name='folders_user_id_49a486_idx'), models.Index(fields=['user', 'parent'], name='folders_user_id_0d7266_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('user', 'path'), name='unique_user_folder_path'),
        ),
    ]
