# Generated by Django 5.0.14 on 2025-12-11 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=50)),
                ('thread_id', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipients', models.JSONField(default=list)),
                ('snippet', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('has_attachments', models.BooleanField(default=False)),
                ('is_classified', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='folders.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '메일',
                'verbose_name_plural': '메일들',
                'db_table': 'mails',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'gmail_id'], name='mails_user_id_c74018_idx'), models.Index(fields=['user', 'folder', '-received_at'], name='mails_user_id_28acc8_idx'), models.Index(fields=['user', 'is_read', '-received_at'], name='mails_user_id_9d368c_idx'), models.Index(fields=['user', 'is_classified'], name='mails_user_id_38b63a_idx'), models.Index(fields=['user', '-received_at'], name='mails_user_id_7623a7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mail',
            constraint=models.UniqueConstraint(fields=('user', 'gmail_id'), name='unique_user_gmail_id'),
        ),
    ]
